### ISSUE TITLE
Post search url is not working 

### ISSUE THREAD

**Issue by vinod1988** [mangrep/ifsc-rest-api#10]
Hi Team,

I am just testing this URL https://api.techm.co.in/api/bank/search/likeBranchName
 and using the post method and passing all the details as per doc. But on the response, the error is coming. I am attaching the screenshot as well for better understand. I am also set the header content as well as per the doc. I am using a postman 

![header content](https://user-images.githubusercontent.com/1991533/30166514-2c0d6038-9401-11e7-804e-b743da58db55.png)
![post content](https://user-images.githubusercontent.com/1991533/30166515-2c0d5d54-9401-11e7-8d9b-7a78808b5a1e.png)

**Comment by mangrep** [comment]
you need to pass data in body not as form-parms. 

Use raw section of postman and pass

{
   "bankName":"ANDHRA BANK", 
   "branchName":"GHANT", 
   "source":"xyz.com"  
 }

**Comment by mangrep** [comment]
this is not an issue.

**Comment by vinod1988** [comment]
@mangrep Thanks for the reply.  on postman raw is working. Thank you so much.
