### ISSUE TITLE
It stopped working after a week

### ISSUE THREAD

**Issue by mehulchauhan31** [mangrep/ifsc-rest-api#4]
We have incorporate IFSC rest api in our web module. suddenly it stopped. It show error message  : "Daily request limit exceeded."  although we are trying it first time in a day.

**Comment by mangrep** [comment]
Hi Mehul,

Thanks for the update.  I have fixed the issue, Please test and let me know If problem persists.

**Comment by mehulchauhan31** [comment]
Hi Magrep,

Thanks for your quick response. It started Working Properly. thanks a lot...
