### ISSUE TITLE
Python Wrapper for API's

### ISSUE THREAD

**Issue by PSanni** [mangrep/ifsc-rest-api#6]
Hi, 
I have written API's wrapper library for python. 
https://github.com/PSanni/Python_Bank_Wrapper

**Comment by ghost** [comment]
Hi Manish,
I have written API wrapper for Javascript and Java. 
## JavaScript
This can be used with both nodejs server side as well on client side.
[https://github.com/arjunnayak0705/js-indian-bank-api](https://github.com/arjunnayak0705/js-indian-bank-api)
## Java
[https://github.com/arjunnayak0705/java-indian-bank-api-wrapper](https://github.com/arjunnayak0705/java-indian-bank-api-wrapper)

**Comment by mangrep** [comment]
thanks @PSanni  @arjunnayak0705 for your effort, I will soon update the docs.
