### ISSUE TITLE
Data Inconsistent

### ISSUE THREAD

**Issue by ghost** [mangrep/ifsc-rest-api#7]
Hi 
When I hit this endpoint [http://api.techm.co.in/api/listbranches/Yes%20bank](http://api.techm.co.in/api/listbranches/Yes%20bank) I get a branch named "ABIDS" as a first record. 

When I try to get details of that branch by hitting this endpoint [https://api.techm.co.in/api/getbank/YES%20BANK/ABIDS](https://api.techm.co.in/api/getbank/YES%20BANK/ABIDS)

` {"status":"failed","message":"No data found"} `
Even for 2nd branch name which is "HYDERABAD" and Third branch and many more
Is there a problem ?

**Comment by mangrep** [comment]
Hi Arjun,


You are not calling the route with proper branch name. You shoud pass **ABIDS, HYDERABAD** insted of passing only **ABIDS**.

**Comment by ghost** [comment]
I mistook ABIDS, HYDERABAD for two different records..
Thank you.
