### ISSUE TITLE
Server is not responding

### ISSUE THREAD

**Issue by suraj-miha** [mangrep/ifsc-rest-api#8]
I integrated the service a day back and was surprised to find that it isn't working today. None of the APIs or the techm.co.in is responding. Does this happen quite frequently? If yes, I might have to find another solution.

**Comment by mangrep** [comment]
Hi @MiHaDevs,

There is some issue with load balancer. I have done a temporary fix. It is working for me. Please check if it is working for you or not?

**Comment by mangrep** [comment]
Hi @MiHaDevs,


Issue has been fixed. Please check at your end if everything is working fine.
