### ISSUE TITLE
SBI details not updated

### ISSUE THREAD

**Issue by itcurs** [mangrep/ifsc-rest-api#9]
Hi,

Can you please download the latest list from RBI website and update the SBI list.

for example SBIN0021107 does not return any value

Great job!
Thanks!

**Comment by mangrep** [comment]
Hi,

SBI has updated IFSC code of 1300+ branches.
http://www.thehindu.com/business/Industry/sbi-changes-names-ifsc-codes-of-around-1300-branches/article21389380.ece

I will update our DB once the updated list is available on RBI website.

**Comment by mangrep** [comment]
done
